### ISSUE TITLE
Strict type checkings

### ISSUE THREAD

**Issue by tmjee** [tmjeee/fuyuko#100]
Strict type checkings 

tsconfig-base.json 
```
  "compilerOptions": {
     "strict": true,
     "strictNullChecks": true
  }
```

and angular's tsconfig should have
```
"angularCompilerOptions" {
   "fullTemplateTypeCheck": true,
   "strictTemplates": true,
   "strictInjectParameters": true
}
```

**Comment by tkjee** [comment]
Done all, except for 
```
"strictNullChecks": true
 ```
as this would take too long. The whole code base was not designed to separate null , undefined from defined object / primitives
